version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo "Zipping deployment package..."
      - echo "Current Dir is " $PWD
      - cd git_cicd/pythonProject/easy_common_libraries/
      - zip -g deployment_package.zip lambda_function.py

      - cd  git_cicd/pythonProject/easy_common_libraries/python
      - echo "Current Dir is " $PWD
      - zip -r9 ../python_package.zip .
      - cd ..
  post_build:
    commands:
      - echo "Updating Lambda function ..."
      - echo "Current Dir is " $PWD
      - ls -ltr $PWD/*
      
      - aws lambda publish-layer-version --layer-name math-layer-for-lambda \
        --description "Math layer" \
        --license-info "MATH" \
        --zip-file fileb://python.zip \
        --compatible-runtimes python3.12 python3.11 \
        --compatible-architectures "arm64" "x86_64"

      - aws lambda create-function --function-name lambdaFromCICDNewLayer --runtime python3.12 \
        --handler lambda_function.lambda_handler --role arn:aws:iam::120582745863:role/awsLambdaFullAccess \
        --zip-file fileb://deployment_package.zip\ 
        --layers math-layer-for-lambda


      - echo "Deployment complete!"