version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo "Zipping deployment package..."
      - echo "Current Dir is " $PWD
      - cd  git_cicd/pythonProject/easy_common_libraries/package
      - echo "Current Dir is " $PWD
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating Lambda function ..."
      - echo "Current Dir is " $PWD
      - ls -ltr *
      - aws lambda update-function-code --function-name lambdaFromCICD --zip-file fileb://git_cicd/pythonProject/easy_common_libraries/deployment_package.zip
      - echo "Deployment complete!"