version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - echo "Current Dir is " $PWD
      - cd git_cicd/pythonProject/easy_common_libraries/
      - pip install -r requirements.txt -t python
      - ls -ltr $PWD/*
  build:
    commands:
      - echo "Zipping deployment package..."
      - echo "Current Dir is " $PWD
      - cd python
      - zip -r9 ../python_package.zip .
      - cd ..
      - ls -ltr $PWD/*
      - echo "Current Dir is " $PWD
      - zip -r9 deployment_package.zip lambda_function.py

  post_build:
    commands:
      - echo "Updating Lambda function ..."
      - echo "Current Dir is " $PWD
      - ls -ltr $PWD/*
      - aws lambda publish-layer-version --layer-name numpy-layer-for-lambda --description "Numpy layer" --license-info "MATH" --zip-file fileb://python_package.zip --compatible-runtimes python3.12 python3.11 --compatible-architectures "arm64" "x86_64"
      - layerARN=$(aws lambda list-layer-versions --layer-name math-layer-for-lambda --query 'LayerVersions[0].LayerVersionArn')
      - echo "Layer Name is ${layerARN}"
      - layerARN=`echo ${layerARN} | sed "s/\"//g"`
      - aws lambda create-function --function-name lambdafForTranposeNumpyLayer --runtime python3.12 --handler lambda_function.lambda_handler --role arn:aws:iam::120582745863:role/awsLambdaFullAccess --zip-file fileb://deployment_package.zip --layers=${layerARN}
      - echo "Deployment complete!"